'''print("***********************\n student details\n***********************")
a=input("student name:")
b=input("roll no:")
c=input("college:")
d=input("department:")
Tam=int(input("Tam:"))
Eng=int(input("Eng:"))
Ma=int(input("Mat:"))
Sc=int(input("sci:"))
SS=int(input("ss:"))
print("***********************\n student Result\n***********************")
print("student name:",a)
print("roll no:",b)
print("college:",c)
print("department:",d)
print("Total= ",Tam+Eng+Ma+Sc+SS)
print("Average= ",Tam+Eng+Ma+Sc+SS/5)'''

'''print("hiii,",end=" ")
print("hello,",end=" ")
print("how are you?",end=" ")
print("im abinaya.",end=" ")
print("im from aec.",end=" ")
print("and my department is cse.",end=" ")
print("my first language is tamil",end=" ")
print("and my second language is english",end=" ")
print("i studied in vallalar higher secondary school at melacavery,",end=" ")
print("short time goal is finished my be.cse without nil arrear.",end=" ")
print("my hobbies is playing games.",end=" ")'''

a=input("food name:")
i=int(input("quantity:"))
price=int(input("f price"))
tot= i*price
print("Bill amt",tot)
