'''print("***********************\n student details\n***********************")
a=input("student name:")
b=input("roll no:")
c=input("college:")
d=input("department:")
Tam=int(input("Tam:"))
Eng=int(input("Eng:"))
Ma=int(input("Mat:"))
Sc=int(input("sci:"))
SS=int(input("ss:"))
print("***********************\n student Result\n***********************")
print("student name:",a)
print("roll no:",b)
print("college:",c)
print("department:",d)
print("Total= ",Tam+Eng+Ma+Sc+SS)
print("Average= ",Tam+Eng+Ma+Sc+SS/5)'''

'''print("hiii,",end=" ")
print("a,",end=" ")
print("b",end=" ")
print("c,",end=" ")
print("d",end=" ")
print("e",end=" ")
print("f",end=" ")
print("g",end=" ")
print("h",end=" ")
print("i",end=" ")
print("j",end=" ")'''

a=input("food name:")
qty=int(input("quantity:"))
price=int(input(" price"))
tot= qty*price
print("you have to pay Rs.₹",tot)
